### ISSUE TITLE
#detect description and example

### ISSUE THREAD

**Issue by blakegearin** [learn-co-curriculum/ruby-search-enumerators#10]
I think the example of detect needs to be changed slightly. It says #detect "will only return the first element that makes the block true," but doesn't specify if it returns the position in the array that is true or the data in the array that evaluates to true.

This also proves to be confusing in the example, because one might not know if this `[1,2,3].detect{|i| i.odd?} #=> 1` is returning 1 because it's the position in the array (which I realize is not the case or it would return 0, but new coders might forget) or the data "1" in the array. I hope that makes sense!

**Comment by SophieDeBenedetto** [comment]
hi @blakebuthod, thanks for your input. I'm going to go ahead and close this issue. I think the definition provided, plus the examples given should be enough to make `#detect` clear.
