### ISSUE TITLE
Further Practice if Supplied Would Be Appreciated

### ISSUE THREAD

**Issue by alleyben** [learn-co-curriculum/ruby-search-enumerators#8]
Better familiarity with boolean and search enumerables would enable their more efficient use in the game_status lab. I suggest having an intermediate lab between the learning of the enumerables and the implementation of them in the tic-tac-toe program. This lab could put into practice each one individually and ideally require that a couple of them be used in conjunction in order to better see their uses and limitations. The syntax of using them conjoined in the game_status lab is giving me a lot of trouble because I feel like I went from learning bits (taking nibbles) to extrapolating a lot (biting off a hunk, perhaps more than I can chew).

**Comment by AnnJohn** [comment]
thanks @modalfish for the suggestion. We're revising our Ruby content between now and the end of June so will keep this suggestion open and hopefully can add more practice. thanks again!
